### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by McSinyx** [amalhtait/NormAFE#1]
I am one of the volunteers at CICLing who is interested in your work. Although I noticed that while your poster said this piece of software was open source, I couldn't find any notice allowing modification and redistribution. Thus, this work cannot be seen as [open source software](https://opensource.org/osd-annotated) (I humbly assume that the term *open source* was mistakenly understood as *with source code open for reading*).

It would be fantastic if you and your team could relicense this under a free/libre and open source software license, as your organization @OpenEdition has always been doing. This way development will be a lot more effective (as more can join to help) and users' freedom in software usage will be improved.

(Personally I want to help to improve the user experience a bit, i.e. handle arguments more flexibly, but I do not think that it is 100% legal to fork a project which doesn't explicitly declare so.)

**Comment by amalhtait** [comment]
Thank you for the comment, cause it's a very important point.
The Tool is made to be open source, I just need to check with OpenEdition to be sure that i can make it officially open source on my github, or It will be licenced as open source only on their github (https://github.com/OpenEdition). It wont take long, a couple of weeks maximum, and we'll share the new licensing.
In the meantime, It's "source code open for reading" since I wanted to present and share during the conference.

**Comment by amalhtait** [comment]
Done, I got a reply from OpenEdition and it's now officially Open Source on my github :)

**Comment by McSinyx** [comment]
Thank you for your fast response. However, generally you will also need to add the license file to the repo and and licensing header the the source files, as well as diclaimer by @OpenEdition: https://www.gnu.org/licenses/gpl-howto.en.html

Thank you for your decision to liberalize the software. Additional question, can [the model hosted at lsis](https://cloud.lsis.org/index.php/s/a0dZ6qg3MpiZfaJ) be freely (as in freedom) used too?
